---
title: "iteration in class"
output: html_document
date: "2025-10-28"
---

```{r}
library(tidyverse)
library(rvest)
set.seed(1)
```


```{r}
list_norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 5),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )

is.list(list_norms)
```



```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```


```{r}
mean_and_sd(list_norms[[1]])
mean_and_sd(list_norms[[2]])
mean_and_sd(list_norms[[3]])
mean_and_sd(list_norms[[4]])
```


```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}
```


use map to do the same thing

```{r}
output = map(list_norms, mean_and_sd)
```

CHeck out some `map` variants

```{r}
map_dfr(list_norms, mean_and_sd, .id = "sample")

map_dbl(list_norms, median)
```


## look at weather data

```{r}
library(p8105.datasets)
data("weather_df")
```

```{r}
weather_df |> 
  filter(name == "CentralPark_NY") |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point() +
  geom_smooth(method = "lm")
```


```{r}
weather_df |> 
  filter(name == "CentralPark_NY") |>
  lm(tmax ~ tmin, data = _)
```

## Let's iterate

```{r}
weather_nest =
  weather_df |> 
  nest(data = date:tmin)
```


```{r}
lm(tmax ~ tmin, data = pull(weather_nest, data)[[1]])
lm(tmax ~ tmin, data = pull(weather_nest, data)[[2]])
lm(tmax ~ tmin, data = pull(weather_nest, data)[[3]])
```


Do this using `map`

```{r}
weather_lm = function(df)
  
  lm(tmax ~ tmin, data = df)
```


```{r}
map(pull(weather_nest, data), weather_lm)
```


```{r}
weather_nest |> 
  mutate(
    lm_fits = map(data, weather_lm)
  )
```








