---
title: "iterations_listicols"
output: github_document
---


```{r}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6 ,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "virids"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```


## Lists

You can put anything in a list.

```{r}
l = list(
vec_numeric = 5: 8,
vec_logical = c(TRUE, TRUE, FALSE, TRUE, FALSE, FALSE),
mat = matrix(1:8, nrow = 2, ncol = 4),
summary = summary(rnorm(100))
)
```

access things in the list
```{r}
l
l$vec_numeric
l[[1]]

mean(l[["vec_numeric"]])
```

## `for` loop

Create a new list.

```{r}
list_norm =
  list(
    a = rnorm(20, mean = 3, sd = 1),
    b = rnorm(30, mean = 0, sd = 5),
    c = rnorm(40, mean = 10, sd = .2),
    d = rnorm(20, mean = -3, sd = 1)
  )
```


```{r}
list_norm
```

Pause and get my old function.

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

I can apply that function to each element

```{r}
list_norm[[1]]
list_norm[[2]]

mean_and_sd(list_norm[[1]])
mean_and_sd(list_norm[[2]])

```

Let's use a for a loop:

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
output[[i]] = mean_and_sd(list_norm[[i]])
}

```


## Let's try map!

```{r}
output = map(list_norm, mean_and_sd)
```

what if you want a different function?

```{r}
output = map(list_norm, median)
```


```{r}
output = map_dbl(list_norm, median)
```


```{r}
output = map_df(list_norm, mean_and_sd)
```

```{r}
output = map_df(list_norm, mean_and_sd, .id = "input")
```






























