---
title: "review_viz2"
output: github_document
---

```{r}
library(tidyverse)
library(patchwork)
```


```{r}
library(p8105.datasets)
data("weather_df")

weather_df
```

Remeber this plot?

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5)

```


## Labels 

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = " Temperature plot",
    x = "minimum daily temperature (C)",
    y = "maximum daily temperature (C)",
    caption = "Data from rnoaa package; temperatures in 2017"
  )

```


## Scales

Star with the same plot
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = " Temperature plot",
    x = "minimum daily temperature (C)",
    y = "maximum daily temperature (C)",
    caption = "Data from rnoaa package; temperatures in 2017"
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15 C", "0", "15")
  ) + 
  scale_y_continuous(
    position = "right"
  )


```


Look at color scales

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = " Temperature plot",
    x = "minimum daily temperature (C)",
    y = "maximum daily temperature (C)",
    caption = "Data from rnoaa package; temperatures in 2017"
  ) +
  scale_color_hue(
    name = "Location",
    h = c(100, 300))

```


lets try something different


```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = " Temperature plot",
    x = "minimum daily temperature (C)",
    y = "maximum daily temperature (C)",
    caption = "Data from rnoaa package; temperatures in 2017"
  ) +
  viridis::scale_color_viridis(
    name = "location",
    discrete = TRUE
  )
```

## Themes

shift the legend

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = " Temperature plot",
    x = "minimum daily temperature (C)",
    y = "maximum daily temperature (C)",
    caption = "Data from rnoaa package; temperatures in 2017"
  ) +
  viridis::scale_color_viridis(
    name = "location",
    discrete = TRUE) +
  theme(legend.position = "bottom")
```

change the overall features

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = " Temperature plot",
    x = "minimum daily temperature (C)",
    y = "maximum daily temperature (C)",
    caption = "Data from rnoaa package; temperatures in 2017"
  ) +
  viridis::scale_color_viridis(
    name = "location",
    discrete = TRUE) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

must put theme_minimal FIRST 

## Setting options

he does this before he starts

```{r, eval = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d()

```


## Data args in `geom`

```{r}
central_park =
  weather_df |> 
  filter(name == "CentralPark_NY")

molokai =
  weather_df |> 
  filter(name == "Molokai_HI")

ggplot(data = molokai, aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = central_park)

```















