---
title: "review_eda"
subtitle: "Exploratory Analysis"
output: github_document
---

```{r}
library(tidyverse)
```


```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d()

```

## Load weather data set

```{r}
library(p8105.datasets)
data("weather_df")

weather_df = 
  weather_df |> 
  mutate(month = lubridate::floor_date(date, unit = "month"))

```


## `group_by`

```{r}
weather_df |> 
  group_by(name, month) |> 
  ungroup()

```


## counting
counting month and name observations

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(n_obs = n ())
  
```

we can use `count`

```{r}
weather_df |> 
  count(name, month, name = "n_obs")
```

**never** use base R's `table`

other helpful counters

```{r}
weather_df |> 
  group_by(month) |> 
  summarize(n_obs = n(),
            n_days = n_distinct(date))
  
```

## A digression on 2x2 tables

```{r}
weather_df |> 
  filter(name != "Molokai_HI") |> 
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not cold",
      TRUE    ~ ""
    )
  ) |> 
  janitor::tabyl(name, cold)
```











