---
title: "wrangle2_from_web"
output: github_document
---

```{r}
library(tidyverse)

library(rvest)

library(httr)
```

##Scrape a table!

I want the first table from [this page] (http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm)


read in the html
```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)
```

extract the table(s); focus on the first one

this first is all 5 tables
```{r}
drug_use_html |> 
  html_table()
```

now this is 1 table.
```{r}
table_marj = 
  drug_use_html |> 
  html_table() |> 
  first() 
```

remove the "words"not" first row that is useless for us
```{r}
table_marj = 
  drug_use_html |> 
  html_table() |> 
  first() |>
  slice(-1) 

table_marj
```


## Star wars movie info

I want the data from [here]("https://www.imdb.com/list/ls070150896/")

```{r}
url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(url)

```

Grab elements that I want

```{r}
title_vec =
  swm_html |> 
  html_elements(".ipc-title-link-wrapper .ipc-title__text--reduced") |> 
  html_text()


metascore_vec = 
  swm_html |>
  html_elements(".metacritic-score-box") |>
  html_text()

runtime_vec = 
  swm_html |>
  html_elements(".dli-title-metadata-item:nth-child(2)") |>
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    score = metascore_vec,
    runtime = runtime_vec)

```


## Get some water data

This is coming from an API

```{r}
nyc_water =
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |>
  content("parsed")

nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") |> 
  content("text") |>
  jsonlite::fromJSON() |>
  as_tibble()
```


## BRFSS
same thing different data

```{r}
brfss_2010 = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv", 
      query = list("$limit"= 5000)) |> 
  content("parsed")
```














